name: "ReqCH CI"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  MIX_ENV: test

jobs:
  test:
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:24.10
        ports:
          - "8123:8123"
          - "9000:9000"

    strategy:
      matrix:
        include:
          - otp_version: "25.3"
            elixir_version: "1.14"

          - otp_version: "27.1.2"
            elixir_version: "1.17"

    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}

      - run: mix deps.get
      - run: mix deps.compile
      - name: Run tests
        run: mix test --warnings-as-errors

      - name: Compile once again but without optional deps
        run: mix compile --force --warnings-as-errors --no-optional-deps

  format:
    runs-on: ubuntu-latest
    name: mix format
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          elixir-version: "1.17"
      - run: mix format --check-formatted
